import { AuthContainer } from '@/components/Auth';
import { MuiThemeProvider } from '@/components/Mui/MuiThemeProvider';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ja' suppressHydrationWarning>
			<body>
				<ToastContainer theme='dark' position='top-center' />
				<Suspense>
					<MuiThemeProvider>
						<AuthContainer />
						<main>{children}</main>
					</MuiThemeProvider>
				</Suspense>
			</body>
		</html>
	);
}
