import { MuiThemeProvider } from '@/components/Mui/MuiThemeProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body>
				<MuiThemeProvider>{children}</MuiThemeProvider>
			</body>
		</html>
	);
}
